import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.ts'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#ff1744',
        'secondary-container': '#c5020b',
        'on-error': '#690005',
        'primary-fixed': '#d8e2ff',
        'inverse-on-surface': '#313030',
        'surface-container-low': '#1c1b1b',
        'surface-variant': '#353534',
        surface: '#131313',
        secondary: '#ffb4aa',
        primary: '#ff5252',
        'tertiary-fixed': '#ffdbcc',
        'on-primary-fixed-variant': '#004493',
        'surface-container-highest': '#353534',
        'on-tertiary-fixed': '#351000',
        'on-secondary-container': '#ffd2cc',
        'secondary-fixed-dim': '#ffb4aa',
        'outline-variant': '#414755',
        'on-secondary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#7c2e00',
        'tertiary-fixed-dim': '#ffb595',
        'inverse-surface': '#e5e2e1',
        'on-secondary': '#690003',
        'surface-container': '#201f1f',
        outline: '#8b90a0',
        'on-background': '#e5e2e1',
        'surface-bright': '#3a3939',
        'surface-tint': '#ff5252',
        'secondary-fixed': '#ffdad5',
        'on-primary-container': '#ffffff',
        'on-error-container': '#ffdad6',
        error: '#ffb4ab',
        'surface-dim': '#131313',
        'tertiary-container': '#ef6719',
        background: '#131313',
        tertiary: '#ffb595',
        'on-secondary-fixed-variant': '#930005',
        'inverse-primary': '#005bc1',
        'on-surface': '#e5e2e1',
        'error-container': '#93000a',
        'surface-container-high': '#2a2a2a',
        'surface-container-lowest': '#0e0e0e',
        'primary-fixed-dim': '#adc6ff',
        'on-tertiary': '#571e00',
        'on-surface-variant': '#c1c6d7',
        'on-tertiary-container': '#4c1a00',
        'on-primary-fixed': '#001a41',
        'on-primary': '#002e69',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        'section-gap': '160px',
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg-mobile': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
